[project]
name = "realsteel"
sdk_version = "0.10.0"
game_root = "assets"

[entrypoint]
file_path = "assets/default.xex"
out_directory_path = "generated/default"
includes = [
	"realsteel_config.toml",
]
